name: Deploy to Package Registry
on:
  pull_request:
    branches:
      - develop
      - master
    types: [closed]
jobs:
  deploy:
    name: Deploy to GitHub Package Registry
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set NPM Scope
        run: echo "SCOPE=@${GITHUB_REPOSITORY_OWNER}" >> $GITHUB_ENV
      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: https://npm.pkg.github.com
          scope: ${{ env.SCOPE }}
      - name: Install Dependencies
        run: bun install --frozen-lockfile --ignore-scripts
      - name: Build
        run: bun run build
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://npm.pkg.github.com
          scope: ${{ env.SCOPE }}
      - name: Deploy
        run: npm publish --access public --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
