name: Create Pull Request

on:
  push:
    branches:
      - 'features/**'
      - 'fix/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  create:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          git fetch origin $BRANCH_NAME:$BRANCH_NAME
      - name: Get first commit message
        id: first_commit
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          FIRST_COMMIT_MSG=$(git log origin/develop..$BRANCH_NAME --pretty=format:%s | tail -n 1)
          if [ -z "$FIRST_COMMIT_MSG" ]; then
            FIRST_COMMIT_MSG="Auto PR: $BRANCH_NAME to develop"
          fi
          echo "message=$FIRST_COMMIT_MSG" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          PR_EXISTS=$(gh pr list --base develop --head "$BRANCH_NAME" --json number --jq 'length')
          if [ "$PR_EXISTS" -eq 0 ]; then
            FIRST_COMMIT_MSG=$(git log origin/develop..$BRANCH_NAME --pretty=format:%s | tail -n 1)
            if [ -z "$FIRST_COMMIT_MSG" ]; then
              FIRST_COMMIT_MSG="Auto PR: $BRANCH_NAME to develop"
            fi
            gh pr create --base develop --head "$BRANCH_NAME" --title "$FIRST_COMMIT_MSG" --body "This PR was automatically created by GitHub Actions." --draft
          else
            echo "PR already exists."
          fi
