name: Create Pull Request

on:
  push:
    branches:
      - 'features/**'
      - 'fix/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  create:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch develop branch
        run: git fetch origin develop:refs/remotes/origin/develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          title: Auto PR: ${{ github.ref_name }} to develop
          body: This PR was automatically created by GitHub Actions.
          draft: true
